# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\blog\LearnQListWidgetEmployee\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 696)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQListWidgetEmployee\\LearnQListWidgetEmployee/Images/K244060766.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 281, 41))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 255);")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 591, 141))
        self.groupBox.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 71, 21))
        self.label_3.setObjectName("label_3")
        self.radioButonWoman = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButonWoman.setGeometry(QtCore.QRect(160, 110, 111, 31))
        self.radioButonWoman.setObjectName("radioButonWoman")
        self.lineEditname = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditname.setGeometry(QtCore.QRect(160, 30, 411, 31))
        self.lineEditname.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.lineEditname.setObjectName("lineEditname")
        self.radioButtonMan = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonMan.setGeometry(QtCore.QRect(380, 110, 111, 31))
        self.radioButtonMan.setObjectName("radioButtonMan")
        self.lineEdit_email = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_email.setGeometry(QtCore.QRect(160, 70, 411, 31))
        self.lineEdit_email.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 591, 101))
        self.groupBox_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_new = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_new.setGeometry(QtCore.QRect(20, 30, 121, 61))
        self.pushButton_new.setStyleSheet("color: rgb(0, 0, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQListWidgetEmployee\\LearnQListWidgetEmployee/Images/add.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_new.setIcon(icon1)
        self.pushButton_new.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_new.setObjectName("pushButton_new")
        self.pushButton_save = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_save.setGeometry(QtCore.QRect(160, 30, 121, 61))
        self.pushButton_save.setStyleSheet("color: rgb(0, 0, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQListWidgetEmployee\\LearnQListWidgetEmployee/Images/save.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_save.setIcon(icon2)
        self.pushButton_save.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_close = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_close.setGeometry(QtCore.QRect(450, 30, 121, 61))
        self.pushButton_close.setStyleSheet("color: rgb(0, 0, 0);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQListWidgetEmployee\\LearnQListWidgetEmployee/Images/remove.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_close.setIcon(icon3)
        self.pushButton_close.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_delete.setGeometry(QtCore.QRect(310, 30, 121, 61))
        self.pushButton_delete.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQListWidgetEmployee\\LearnQListWidgetEmployee/Images/delete.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_delete.setIcon(icon4)
        self.pushButton_delete.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 330, 591, 321))
        self.groupBox_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidgetEmployee = QtWidgets.QListWidget(parent=self.groupBox_3)
        self.listWidgetEmployee.setGeometry(QtCore.QRect(20, 40, 551, 261))
        self.listWidgetEmployee.setObjectName("listWidgetEmployee")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dương Thanh Bình K244060766"))
        self.label.setText(_translate("MainWindow", "Employee Management"))
        self.groupBox.setTitle(_translate("MainWindow", "Employee Information:"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.radioButonWoman.setText(_translate("MainWindow", "Woman"))
        self.radioButtonMan.setText(_translate("MainWindow", "Man"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Action:"))
        self.pushButton_new.setText(_translate("MainWindow", "New"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.groupBox_3.setTitle(_translate("MainWindow", "List of Employee:"))
