# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\blog\LearnQTableWidgetProduct\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(438, 502)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 200, 411, 161))
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 91, 21))
        self.label_3.setObjectName("label_3")
        self.lineEditID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditID.setGeometry(QtCore.QRect(140, 20, 261, 31))
        self.lineEditID.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.lineEditID.setObjectName("lineEditID")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_name.setGeometry(QtCore.QRect(140, 70, 261, 31))
        self.lineEdit_name.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_price = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_price.setGeometry(QtCore.QRect(140, 120, 261, 31))
        self.lineEdit_price.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 127);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 370, 411, 81))
        self.groupBox_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 127);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonnew = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonnew.setGeometry(QtCore.QRect(30, 30, 101, 41))
        self.pushButtonnew.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQTableWidgetProduct\\Images/new.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonnew.setIcon(icon)
        self.pushButtonnew.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonnew.setObjectName("pushButtonnew")
        self.pushButtonsave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonsave.setGeometry(QtCore.QRect(150, 30, 101, 41))
        self.pushButtonsave.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQTableWidgetProduct\\Images/save.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonsave.setIcon(icon1)
        self.pushButtonsave.setIconSize(QtCore.QSize(48, 48))
        self.pushButtonsave.setObjectName("pushButtonsave")
        self.pushButton_remove = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_remove.setGeometry(QtCore.QRect(270, 30, 111, 41))
        self.pushButton_remove.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\DTB\\uel\\HK1\\tu duy lap trinh\\DuongThanhBinh_K244060766_Module28\\blog\\LearnQTableWidgetProduct\\Images/trash.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_remove.setIcon(icon2)
        self.pushButton_remove.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 411, 181))
        self.groupBox_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 127);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidgetProduct = QtWidgets.QTableWidget(parent=self.groupBox_3)
        self.tableWidgetProduct.setGeometry(QtCore.QRect(10, 20, 391, 151))
        self.tableWidgetProduct.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.tableWidgetProduct.setObjectName("tableWidgetProduct")
        self.tableWidgetProduct.setColumnCount(3)
        self.tableWidgetProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidgetProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidgetProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidgetProduct.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 438, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Product Details:"))
        self.label.setText(_translate("MainWindow", "Product Id:"))
        self.label_2.setText(_translate("MainWindow", "Product Name:"))
        self.label_3.setText(_translate("MainWindow", "Unit Price:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Actions"))
        self.pushButtonnew.setText(_translate("MainWindow", "New"))
        self.pushButtonsave.setText(_translate("MainWindow", "Save"))
        self.pushButton_remove.setText(_translate("MainWindow", "Remove"))
        self.groupBox_3.setTitle(_translate("MainWindow", "List of Products:"))
        item = self.tableWidgetProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidgetProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.tableWidgetProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Unit Price"))
