# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\Chuong4_file\Project85\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 338)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 411, 51))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(255, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 111, 31))
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 111, 31))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(150, 110, 281, 31))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setEnabled(True)
        self.lineEdit_password.setGeometry(QtCore.QRect(150, 150, 281, 31))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setDragEnabled(False)
        self.lineEdit_password.setClearButtonEnabled(False)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.checkBox_save = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_save.setGeometry(QtCore.QRect(150, 200, 281, 21))
        self.checkBox_save.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.checkBox_save.setObjectName("checkBox_save")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(150, 230, 111, 31))
        self.pushButton_login.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(290, 230, 111, 31))
        self.pushButton_exit.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DuongThanhBinh_K244060766"))
        self.label.setText(_translate("MainWindow", "Login Screen"))
        self.label_2.setText(_translate("MainWindow", "User Name:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.lineEdit_username.setText(_translate("MainWindow", "teo"))
        self.lineEdit_password.setText(_translate("MainWindow", "123"))
        self.checkBox_save.setText(_translate("MainWindow", "Save Login Information"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
