# Form implementation generated from reading ui file 'D:\DTB\uel\HK1\tu duy lap trinh\DuongThanhBinh_K244060766_Module28\Chuong6_ThuVien\project117\ui\MainWindow117.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 378)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 301, 31))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lineEdit_Data = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Data.setGeometry(QtCore.QRect(40, 40, 451, 41))
        self.lineEdit_Data.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_Data.setObjectName("lineEdit_Data")
        self.pushButton_calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(40, 90, 451, 51))
        self.pushButton_calculate.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 451, 171))
        self.label_2.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter Data(Comma Seperated)"))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate"))
